---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, "lf"]
      - id: trailing-whitespace
  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: 0.1.2
    hooks:
      - id: tidy-gitignore
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.36.2"
    hooks:
      - id: yamllint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.10.0.1"
    hooks:
      - id: shellcheck
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        additional_dependencies:
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0"
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.5.1
    hooks:
      - id: zizmor
        args: [--persona=pedantic]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - types-PyYAML
