---
name: Build SST within Spack

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  schedule:
    # 0215 daily
    - cron: '15 2 * * *'
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  install-spack:
    name: >-
      os:${{ matrix.os }} /
      sst-version:${{ matrix.sst-spack-version }} /
      python:${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          # not compiling elements with gcc 14.2 is a headache
          # - ubuntu-24.04
          - macos-13
          - macos-14
        sst-spack-version:
          - '13.1.0'
          - '14.0.0'
          - '14.1.0'
          - 'master'
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          # Can't use these with Spack yet
          # - '3.12'
          # - '3.13'
        exclude:
          # Python version not compilable with Apple Clang
          - os: macos-13
            python-version: '3.6'
          - os: macos-14
            python-version: '3.6'
          # Reduce testing load
          - os: macos-13
            python-version: '3.8'
          - os: macos-13
            python-version: '3.9'
          - os: macos-13
            python-version: '3.10'
      fail-fast: false
    permissions:
      packages: write
    steps:
      - name: Install Git (Unix)
        run: |
          if command -v dnf >/dev/null 2>&1; then
              dnf upgrade -y
              dnf install -y git
          elif command -v pacman >/dev/null 2>&1; then
              pacman -Syu --noconfirm
              pacman -S --noconfirm git
          fi
        if: ${{ runner.os != 'Windows' }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
        with:
          persist-credentials: false
      - name: Install system-level dependencies (Unix)
        run: |
          if [[ "${USE_SUDO}" == true ]]; then
              sudo bash .github/workflows/install_os_deps.sh
          else
              bash .github/workflows/install_os_deps.sh
          fi
        env:
          USE_SUDO: true
        shell: bash
        if: ${{ runner.os != 'Windows' }}
      - name: Clone Spack
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
        with:
          persist-credentials: false
          # Take the latest (develop) version.
          repository: berquist/spack
          ref: sst-modernize
          path: spack
      - name: Add Spack to PATH and set mirror name
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
          echo "mirror_name=github-container-registry" >> "${GITHUB_ENV}"
      - name: Find compilers for Spack
        run: |
          spack compiler find --mixed-toolchain
      - name: Print Spack configuration
        run: |
          spack config blame config
          spack debug report
      - name: Repository ownership
        run: |
          git config --global --add safe.directory /__w/sst-spack/sst-spack
      - name: Concretize and install environment
        run: |
          ./run.sh ${{ matrix.sst-spack-version }} ${{ matrix.python-version }}
        env:
          SPACK_OCI_USERNAME: "${{ github.actor }}"
          SPACK_OCI_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
