---
name: Build SST within Spack

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  schedule:
    # 0215 daily
    - cron: '15 2 * * *'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-inside-spack-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  install-spack:
    name: >-
      os:${{ matrix.os }} / sst:${{ matrix.sst-spack-version }} / python:${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # crazy compilation errors
          # - ubuntu-24.04-arm
          - macos-15
          - macos-26
        sst-spack-version:
          - '16.0.0'
          - develop
        python-version:
          - '3.9'
          - '3.14'
      fail-fast: false
    permissions:
      packages: write  # spack.yaml autopushes to remote OCI repo
    steps:
      - name: Clean up disk space
        run: |
          df -h
          sudo rm -rf /__t/*
          sudo rm -rf /usr/lib/jvm
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/dotnet
          if [[ $(uname) != "Darwin" ]]; then
              sudo rm -rf /usr/share/swift
          fi
          df -h
      - name: Install Git
        run: |
          if command -v dnf >/dev/null 2>&1; then
              dnf upgrade -y
              dnf install -y git
          elif command -v apt-get; then
              apt-get update -y --no-install-recommends
              apt-get install -y --no-install-recommends git ca-certificates
          elif command -v pacman >/dev/null 2>&1; then
              pacman -Syu --noconfirm
              pacman -S --noconfirm git
          fi
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          persist-credentials: false
      - name: Install system-level dependencies
        run: |
          if [[ "${USE_SUDO}" == true ]]; then
              sudo bash .github/workflows/install_os_deps.sh
          else
              bash .github/workflows/install_os_deps.sh
          fi
        env:
          USE_SUDO: true
        shell: bash
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639  # v1.2
      - name: Clone Spack
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          persist-credentials: false
          repository: spack/spack
          path: spack
          ref: v1.2.0
      - name: Add Spack to PATH and set mirror name
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
          echo "mirror_name=github-container-registry" >> "${GITHUB_ENV}"
      - name: Clone Spack package repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          persist-credentials: false
          repository: spack/spack-packages
          ref: develop
          path: spack-packages
      - name: Set Spack package repo
        run: |
          spack repo set --destination "${PWD}/"spack-packages builtin
          spack repo list
      - name: Bootstrap Spack
        run: |
          spack bootstrap now
          spack bootstrap status
      - name: Find compilers for Spack
        run: |
          spack compiler find
      - name: Configure Spack to use ccache
        run: |
          spack config add config:ccache:true
      - name: Print Spack configuration
        run: |
          spack config blame config
          spack debug report
      - name: Repository ownership
        run: |
          git config --global --add safe.directory /__w/sst-spack/sst-spack
      - name: Concretize and install environment
        run: |
          ./run.sh "${MATRIX_SST_SPACK_VERSION}" "${MATRIX_PYTHON_VERSION}"
        env:
          MATRIX_SST_SPACK_VERSION: "${{ matrix.sst-spack-version }}"
          MATRIX_PYTHON_VERSION: "${{ matrix.python-version }}"
          SPACK_OCI_USERNAME: "${{ github.actor }}"
          SPACK_OCI_PASSWORD: "${{ secrets.PACKAGE_REPO_TOKEN }}"
