---
name: Build SST within Spack inside containers

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  schedule:
    # 0215 daily
    - cron: '15 2 * * *'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-inside-spack-on-containers-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  install-spack-inside-container:
    name: >-
      image:${{ matrix.image }} / sst:${{ matrix.sst-spack-version }} / python:${{ matrix.python-version }}
    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.image }}
      volumes:
        - /usr/lib:/host/usr/lib
        - /usr/local:/host/usr/local
        - /usr/share:/host/usr/share
    strategy:
      matrix:
        image:
          # Can't use default GCC 16 with Pin
          # https://github.com/berquist/sst-spack/issues/24
          #
          # - archlinux:base-devel-20260503.0.523481@sha256:fdff15f24df062598faebf380430955a9bd2109736e179ebb354f1208f725774
          - rockylinux/rockylinux:8.10.20240528@sha256:e8a49c5403b687db05d4d67333fa45808fbe74f36e683cec7abb1f7d0f2338c6
          # container issues?
          # - rockylinux/rockylinux:9.7.20251123@sha256:53f4c6dcb34e1403bd93207351f0af9a593610faeb7165cb8a037346765199b0
          - ubuntu:jammy-20260509@sha256:4f838adc7181d9039ac795a7d0aba05a9bd9ecd480d294483169c5def983b64d
          - ubuntu:noble-20260410@sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b
          # Can't use default GCC 15 with Pin
          # https://github.com/berquist/sst-spack/issues/24
          #
          # - ubuntu:resolute-20260421@sha256:f3d28607ddd78734bb7f71f117f3c6706c666b8b76cbff7c9ff6e5718d46ff64
        sst-spack-version:
          - '16.0.0'
          - develop
        python-version:
          - '3.9'
          - '3.14'
      fail-fast: false
    permissions:
      packages: write  # spack.yaml autopushes to remote OCI repo
    steps:
      - name: Clean up disk space
        run: |
          df -h
          rm -rf /__t/*
          rm -rf /host/usr/lib/jvm
          rm -rf /host/usr/local/.ghcup
          rm -rf /host/usr/local/lib/android
          rm -rf /host/usr/local/share/powershell
          rm -rf /host/usr/share/dotnet
          rm -rf /host/usr/share/swift
          df -h
      - name: Install Git
        run: |
          if command -v dnf >/dev/null 2>&1; then
              dnf upgrade -y
              dnf install -y git
          elif command -v apt-get; then
              apt-get update -y --no-install-recommends
              apt-get install -y --no-install-recommends git ca-certificates
          elif command -v pacman >/dev/null 2>&1; then
              pacman -Syu --noconfirm
              pacman -S --noconfirm git
          fi
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          persist-credentials: false
      - name: Install system-level dependencies
        run: |
          if [[ "${USE_SUDO}" == true ]]; then
              sudo bash .github/workflows/install_os_deps.sh
          else
              bash .github/workflows/install_os_deps.sh
          fi
        env:
          USE_SUDO: false
        shell: bash
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639  # v1.2
      - name: Clone Spack
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          persist-credentials: false
          # Take the latest (develop) version.
          repository: spack/spack
          path: spack
          ref: e88eef45e3633db6a5705d403acaef552d520fe2
      - name: Add Spack to PATH and set mirror name
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
          echo "mirror_name=github-container-registry" >> "${GITHUB_ENV}"
      - name: Clone Spack package repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          persist-credentials: false
          # Take the latest (develop) version.
          repository: spack/spack-packages
          ref: develop
          path: spack-packages
      - name: Set Spack package repo
        run: |
          spack repo set --destination "${PWD}/"spack-packages builtin
          spack repo list
      - name: Bootstrap Spack
        run: |
          spack bootstrap now
          spack bootstrap status
      - name: Find compilers for Spack
        run: |
          spack compiler find
      - name: Print Spack configuration
        run: |
          spack config blame config
          spack debug report
      - name: Repository ownership
        run: |
          git config --global --add safe.directory /__w/sst-spack/sst-spack
      - name: Concretize and install environment
        run: |
          ./run.sh "${MATRIX_SST_SPACK_VERSION}" "${MATRIX_PYTHON_VERSION}"
        env:
          MATRIX_SST_SPACK_VERSION: "${{ matrix.sst-spack-version }}"
          MATRIX_PYTHON_VERSION: "${{ matrix.python-version }}"
          SPACK_OCI_USERNAME: "${{ github.actor }}"
          SPACK_OCI_PASSWORD: "${{ secrets.PACKAGE_REPO_TOKEN }}"
