---
name: Build SST within Spack

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  schedule:
    # 0215 daily
    - cron: '15 2 * * *'
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  install-spack:
    name: >-
      os:${{ matrix.os }} /
      sst:${{ matrix.sst-spack-version }} /
      python:${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # crazy compilation errors
          # - ubuntu-24.04-arm
          - macos-15
          - macos-26
        sst-spack-version:
          - '16.0.0'
        python-version:
          - '3.9'
          - '3.14'
      fail-fast: false
    permissions:
      packages: write
    steps:
      - name: Clean up disk space
        run: |
          df -h
          sudo rm -rf /__t/*
          sudo rm -rf /usr/lib/jvm
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          df -h
      - name: Install Git (Unix)
        run: |
          if command -v dnf >/dev/null 2>&1; then
              dnf upgrade -y
              dnf install -y git
          elif command -v apt-get; then
              apt-get update -y --no-install-recommends
              apt-get install -y --no-install-recommends git ca-certificates
          elif command -v pacman >/dev/null 2>&1; then
              pacman -Syu --noconfirm
              pacman -S --noconfirm git
          fi
        if: ${{ runner.os != 'Windows' }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false
      - name: Install system-level dependencies (Unix)
        run: |
          if [[ "${USE_SUDO}" == true ]]; then
              sudo bash .github/workflows/install_os_deps.sh
          else
              bash .github/workflows/install_os_deps.sh
          fi
        env:
          USE_SUDO: true
        shell: bash
        if: ${{ runner.os != 'Windows' }}
      - name: Clone Spack
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false
          # Take the latest (develop) version.
          repository: spack/spack
          path: spack
          ref: e88eef45e3633db6a5705d403acaef552d520fe2
      - name: Add Spack to PATH and set mirror name
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
          echo "mirror_name=github-container-registry" >> "${GITHUB_ENV}"
      - name: Clone Spack package repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false
          # Take the latest (develop) version.
          repository: spack/spack-packages
          ref: develop
          path: spack-packages
      - name: Set Spack package repo
        run: |
          spack repo set --destination "${PWD}/"spack-packages builtin
          spack repo list
      - name: Bootstrap Spack
        run: |
          spack bootstrap now
          spack bootstrap status
      - name: Find compilers for Spack
        run: |
          spack compiler find
      - name: Print Spack configuration
        run: |
          spack config blame config
          spack debug report
      - name: Repository ownership
        run: |
          git config --global --add safe.directory /__w/sst-spack/sst-spack
      - name: Concretize and install environment
        run: |
          ./run.sh ${{ matrix.sst-spack-version }} ${{ matrix.python-version }}
        env:
          SPACK_OCI_USERNAME: "${{ github.actor }}"
          SPACK_OCI_PASSWORD: "${{ secrets.PACKAGE_REPO_TOKEN }}"
